version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks: 
      - contentapi
    ports:
      - "1337:1337"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_API_URL=http://backend:1337
    networks:
      - contentapi
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - contentapi
    depends_on:
      - backend
      - frontend

networks:
  contentapi:
    driver: bridge
